/** @type {import('jest').Config} */
module.exports = {
  testMatch: ['**/tests/**/*.test.js'],
  collectCoverageFrom: ['lib/**/*.js'],
  coverageDirectory: 'coverage',
  coverageThreshold: {
    // Per-file thresholds — 85% line coverage floor for all lib/ modules (Phase 51)
    './lib/autopilot.js': { lines: 93, functions: 97, branches: 80 },
    './lib/backend.js': { lines: 95, functions: 100, branches: 88 },
    './lib/cleanup.js': { lines: 92, functions: 96, branches: 80 },
    './lib/commands.js': { lines: 90, functions: 95, branches: 70 },
    './lib/context.js': { lines: 87, functions: 83, branches: 77 },
    './lib/deps.js': { lines: 94, functions: 100, branches: 87 },
    './lib/evolve.js': { lines: 85, functions: 94, branches: 70 },
    './lib/frontmatter.js': { lines: 89, functions: 100, branches: 78 },
    './lib/gates.js': { lines: 98, functions: 100, branches: 82 },
    './lib/long-term-roadmap.js': { lines: 97, functions: 100, branches: 83 },
    './lib/markdown-split.js': { lines: 95, functions: 100, branches: 90 },
    './lib/mcp-server.js': { lines: 90, functions: 85, branches: 55 },
    './lib/parallel.js': { lines: 85, functions: 100, branches: 80 },
    './lib/paths.js': { lines: 95, functions: 100, branches: 95 },
    './lib/phase.js': { lines: 91, functions: 94, branches: 70 },
    './lib/roadmap.js': { lines: 91, functions: 94, branches: 83 },
    './lib/scaffold.js': { lines: 90, functions: 100, branches: 70 },
    './lib/state.js': { lines: 85, functions: 88, branches: 77 },
    './lib/tracker.js': { lines: 85, functions: 89, branches: 70 },
    './lib/utils.js': { lines: 92, functions: 95, branches: 85 },
    './lib/verify.js': { lines: 85, functions: 100, branches: 70 },
    './lib/worktree.js': { lines: 84, functions: 100, branches: 73 },
  },
  testTimeout: 15000,
};
